["汕大"]
"汕大官网" = "https://www.stu.edu.cn/"
"教务系统" = "https://jw.stu.edu.cn"
mystu = "http://my.stu.edu.cn"
"金凤bt" = "http://phoenix.stu.edu.cn/"
"oa系统" = "http://oa.stu.edu.cn"
"邮箱" = "https://partner.outlook.cn/mail/"

["常用"]
bilibili = "https://www.bilibili.com"
"百度" = "https://www.baidu.com"
"抖音" = "https://www.douyin.com/"
